[phases.setup]
nixPkgs = ['nodejs_22', 'python3', 'pixman', 'cairo', 'pango', 'giflib', 'libjpeg']

[phases.install]
cmds = ['npm ci --prefer-offline --no-audit --progress=false']

[start]
cmd = 'node server.js'

